# Generated by Django 4.2.11 on 2024-04-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usermaster',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, db_column='FullName', max_length=100, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=100, null=True)),
                ('confirmpassword', models.CharField(blank=True, db_column='ConfirmPassword', max_length=100, null=True)),
                ('email', models.CharField(db_column='Email', max_length=100)),
                ('mobilenumber', models.CharField(db_column='mobilenumber', max_length=10)),
            ],
            options={
                'db_table': 'usermaster',
                'managed': False,
            },
        ),
    ]
