# Generated by Django 4.2.11 on 2024-04-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermaster',
            options={'managed': True},
        ),
    ]
