# Generated by Django 4.2.11 on 2024-04-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_alter_usermaster_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
