# Generated by Django 4.2.11 on 2024-04-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0003_usermaster_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='countrycode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
