# Generated by Django 4.2.11 on 2024-04-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0004_usermaster_countrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='countrycode',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
